# Configuração para projetos Google Apps Script
# Schema: ./schema/config.schema.json

# Configurações padrão
defaults:
  timeZone: America/Sao_Paulo
  runtimeVersion: V8

# Configurações de caminhos (evita amarramento à estrutura do projeto)
paths:
  src: src
  dist: dist
  templates: templates
  scripts: scripts

# Configurações de projetos padrão (usados quando não há configurações específicas)
defaultProjects:
  # Projeto padrão para planilha de salário
  projeto-tipo-a:
    src: caminho-fonte-a
    output: saida-a
    outputTemplate: '{{year}}-saida-a'
    dependencies:
      - userSymbol: Drive
        version: v3
        serviceId: drive
    sheetsMacros:
      - menuName: 1. AÇÃO PRINCIPAL
        functionName: acaoPrincipal
      - menuName: 2. AÇÃO SECUNDÁRIA
        functionName: acaoSecundaria
  
  # Projeto padrão para planilhas com subchaves
  projeto-tipo-b:
    src: caminho-fonte-b
    output: saida-b
    outputTemplate: '{{year}}-{{key}}-saida-b'
    dependencies:
      - userSymbol: Drive
        version: v3
        serviceId: drive
    sheetsMacros:
      - menuName: 1. AÇÃO PRINCIPAL B
        functionName: acaoPrincipalB
    # Configurações aninhadas para subchaves
    nested:
      subchave-1:
        propriedade: Valor 1
      subchave-2:
        propriedade: Valor 2

# Configurações dos projetos
projects:
  # Projeto de exemplo
  meu-projeto-a:
    src: pasta-fonte-a
    output: saida-a
    # Template para o nome do diretório de saída usando chaves dinâmicas
    outputTemplate: "{{key-1}}-saida-a"
    # Template para o nome do projeto usando chaves dinâmicas
    nameTemplate: "Projeto A {{key-1}} {{ambiente}}"
    dependencies:
      - userSymbol: Drive
        version: v3
        serviceId: drive
    sheetsMacros:
      - menuName: 1. FUNÇÃO PRINCIPAL
        functionName: funcaoPrincipal
      - menuName: 2. FUNÇÃO SECUNDÁRIA
        functionName: funcaoSecundaria
    dev:
      # Chave dinâmica 'ano'
      2024:
        # Aqui o nome será processado usando o template acima
        # e substituindo {{key-1}} por '2024' e {{ambiente}} por 'dev'
        scriptId: 1abc123456789
        linkedFileId: 1abc123456789
    prod:
      # Chave dinâmica 'key-1'
      2024:
        scriptId: 1xyz987654321
        linkedFileId: 1xyz987654321
  
  # Projeto com subchaves aninhadas
  meu-projeto-b:
    src: pasta-fonte-b
    output: saida-b
    # Template para o nome do diretório de saída usando chaves dinâmicas
    outputTemplate: "{{key-1}}-{{key-2}}-saida-b"
    # Template para o nome do projeto usando chaves dinâmicas
    nameTemplate: "Projeto B {{nome_subchave}} {{key-1}} {{ambiente}}"
    dependencies:
      - userSymbol: Drive
        version: v3
        serviceId: drive
    sheetsMacros:
      - menuName: 1. FUNÇÃO PRINCIPAL B
        functionName: funcaoPrincipalB
      - menuName: 2. FUNÇÃO SECUNDÁRIA B
        functionName: funcaoSecundariaB
    # Mapeamento de subchaves para nomes amigáveis
    subchave_mapping:
      subchave-1: Nome Subchave 1
      subchave-2: Nome Subchave 2
      subchave-3: Nome Subchave 3
    dev:
      # Chave dinâmica 'key-1'
      2024:
        # Chave dinâmica 'key-2'
        subchave-1:
          # Aqui o nome será processado usando o template acima
          # e substituindo {{key-1}} por '2024', {{key-2}} por 'subchave-1',
          # {{nome_subchave}} por 'Nome Subchave 1' e {{ambiente}} por 'dev'
          scriptId: 1abc123456789
          linkedFileId: 1abc123456789
          # Variável adicional para usar no template
          nome_subchave: Nome Subchave 1
        subchave-2:
          scriptId: 1def123456789
          linkedFileId: 1def123456789
          nome_subchave: Nome Subchave 2
        subchave-3:
          scriptId: 1ghi123456789
          linkedFileId: 1ghi123456789
          nome_subchave: Nome Subchave 3
    prod:
      # Chave dinâmica 'key-1'
      2024:
        # Chave dinâmica 'key-2'
        subchave-1:
          scriptId: 1jkl123456789
          linkedFileId: 1jkl123456789
          nome_subchave: Nome Subchave 1
        subchave-2:
          scriptId: 1mno123456789
          linkedFileId: 1mno123456789
          nome_subchave: Nome Subchave 2
        subchave-3:
          scriptId: 1pqr123456789
          linkedFileId: 1pqr123456789
          nome_subchave: Nome Subchave 3
