# Configurações globais - Estrutura recomendada
# Schema: ./schema/config.schema.json

defaults:
  # Configurações de templates usando a estrutura recomendada
  templates:
    .clasp-template.json:
      destination-file: .clasp.json
    .claspignore-template.json:
      destination-file: .claspignore
    appsscript-template:
      destination-file: appsscript.json
      keys:
        - timeZone: America/Sao_Paulo
        - runtimeVersion: V8
  
  # Configurações de caminhos
  paths:
    src: ./src
    build: ./build
    dist: ./dist
    templates: ./templates
    scripts: ./scripts
  
  # Estrutura de projetos
  projects-structure:
    example:
      keys:
    salario:
      nested:
        - key: year
    consumo:
      nested:
        - key: year
        - key: pdv

# Configurações dos projetos
projects:
  # Projeto de exemplo sem estrutura aninhada
  example:
    src: example
    output: example
    outputTemplate: example
    nameTemplate: 'Example {{env}}'
    # Ambientes dentro do projeto (nova estrutura recomendada)
    environments:
      dev:
        templates:
          .clasp-template.json:
            destination-file: .clasp.json
            scriptId: dev-example-script-id
        linkedFileId: dev-example-linked-file-id
      prod:
        templates:
          .clasp-template.json:
            destination-file: .clasp.json
            scriptId: prod-example-script-id
        linkedFileId: prod-example-linked-file-id
    mapping:
      keys-template:
        - key: output
          nameTemplate:
            substitutions:
              - example: Example
    dependencies:
      - userSymbol: Drive
        version: v3
        serviceId: drive
    sheetsMacros:
      - menuName: 1. EXEMPLO
        functionName: exemploFunc
  
  # Projeto de salário com estrutura aninhada (ano)
  salario:
    src: planilha-salario
    output: salario
    outputTemplate: '{{year}}-{{output}}'
    nameTemplate: 'Macros {{output}} {{year}} {{env}}'
    nested:
      - key: year
    # Ambientes dentro do projeto (nova estrutura recomendada)
    environments:
      dev:
        # Configurações para o ano 2024
        2024:
          templates:
            .clasp-template.json:
              destination-file: .clasp.json
              scriptId: dev-salario-2024-script-id
          linkedFileId: dev-salario-2024-linked-file-id
      prod:
        # Configurações para o ano 2024
        2024:
          templates:
            .clasp-template.json:
              destination-file: .clasp.json
              scriptId: prod-salario-2024-script-id
          linkedFileId: prod-salario-2024-linked-file-id
    mapping:
      keys-template:
        - key: output
          nameTemplate:
            substitutions:
              - salario: Salário
    dependencies:
      - userSymbol: Drive
        version: v3
        serviceId: drive
    sheetsMacros:
      - menuName: 1. VIRAR MÊS SALARIO
        functionName: virarMesSalario
      - menuName: 2. VIRAR ANO SALARIO
        functionName: virarAnoSalario

  # Projeto de consumo com estrutura aninhada (ano e pdv)
  consumo:
    src: planilha-consumo
    output: consumo
    outputTemplate: '{{year}}-{{pdv}}-{{output}}'
    nameTemplate: 'Macros {{output}} {{pdv}} {{year}} {{env}}'
    nested:
      - key: year
      - key: pdv
    # Ambientes dentro do projeto (nova estrutura recomendada)
    environments:
      dev:
        # Configurações para o ano 2024
        2024:
          # Configurações para cada PDV
          1-cafeteria:
            templates:
              .clasp-template.json:
                destination-file: .clasp.json
                scriptId: dev-consumo-2024-cafeteria-script-id
            linkedFileId: dev-consumo-2024-cafeteria-linked-file-id
          2-saara:
            templates:
              .clasp-template.json:
                destination-file: .clasp.json
                scriptId: dev-consumo-2024-saara-script-id
            linkedFileId: dev-consumo-2024-saara-linked-file-id
      prod:
        # Configurações para o ano 2024
        2024:
          # Configurações para cada PDV
          1-cafeteria:
            templates:
              .clasp-template.json:
                destination-file: .clasp.json
                scriptId: prod-consumo-2024-cafeteria-script-id
            linkedFileId: prod-consumo-2024-cafeteria-linked-file-id
          2-saara:
            templates:
              .clasp-template.json:
                destination-file: .clasp.json
                scriptId: prod-consumo-2024-saara-script-id
            linkedFileId: prod-consumo-2024-saara-linked-file-id
    mapping:
      keys-template:
        - key: output
          nameTemplate:
            substitutions:
              - consumo: Consumo
        - key: pdv
          nameTemplate:
            substitutions:
              - 1-cafeteria: 1.Cafeteria
              - 2-saara: 2.Saara
              - 3-castelo: 3.Castelo
              - 4-stones: 4.Stones
    dependencies:
      - userSymbol: Drive
        version: v3
        serviceId: drive
    sheetsMacros:
      - menuName: 1. VIRAR MÊS CONSUMO
        functionName: virarMesConsumo
      - menuName: 2. VIRAR ANO CONSUMO
        functionName: virarAnoConsumo
